"""monitor_cascade

Revision ID: 87aa1f0849a2
Revises: 82c1c69f8659
Create Date: 2026-04-27 04:02:42.536721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87aa1f0849a2'
down_revision: Union[str, Sequence[str], None] = '82c1c69f8659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('probes_monitor_id_fkey'), 'probes', type_='foreignkey')
    op.create_foreign_key(None, 'probes', 'monitors', ['monitor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'probes', type_='foreignkey')
    op.create_foreign_key(op.f('probes_monitor_id_fkey'), 'probes', 'monitors', ['monitor_id'], ['id'])
    # ### end Alembic commands ###
