"""add check_time field

Revision ID: ee8ab3a22ae8
Revises: 8b48f9f6892e
Create Date: 2026-04-20 22:36:39.186776

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee8ab3a22ae8"
down_revision: Union[str, Sequence[str], None] = "8b48f9f6892e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitors", sa.Column("last_checked_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitors", "last_checked_at")
    # ### end Alembic commands ###
